service: configservice
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 3

  apiGateway:
    apiKeys:
      - testKey
    usagePlan:
      throttle:
        burstLimit: 10
        rateLimit: 5

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: !Join ["/", [ !GetAtt ConfigBucket.Arn, '*'] ]
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: !GetAtt ConfigBucket.Arn

  environment:
    CONFIGBUCKET: !Ref ConfigBucket

functions:
  GetConfig:
    handler: src/lambdas/GetConfig.handler
    events:
      - http:
          path: /config/{stage}/{system}
          method: get
          private: true

resources:
  Resources:
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-configbucket